#!/bin/sh

# VARIABLES
log_file="${EVENT_LOG:-$XDG_CONFIG_HOME/event_log}"
current_time="$(date +%Y.%m.%d-%I:%M:%S)"


# FUNCTIONS
usage() {
cat << -EOF
Usage: elog [option] [messege]
  a, add	Add a new entry
  t, time	Print time elapsed since last entry
  s, show	Show event log

-EOF
}

get_last() {
	last_time="$(grep + $log_file | tail -n 1 | cut -c 3-)"
}

get_elapsed() {
	elapsed="$(( $(date -d $current_time +%s) - $(date -d $last_time +%s) ))"
}

check_file() {
	[ ! -w "$log_file" ] && echo "Event log file doesn't exist" && exit
}

get_times() {
	while [ $elapsed -ge 86400 ]; do
		elapsed="$(( $elapsed - 86400 ))"
		days="$(( $days + 1 ))"
	done
	while [ $elapsed -ge 3600 ]; do
		elapsed="$(( $elapsed - 3600 ))"
		hours="$(( $hours + 1 ))"
	done
	while [ $elapsed -ge 60 ]; do
		elapsed="$(( $elapsed - 60 ))"
		minutes="$(( $minutes + 1 ))"
	done
	
	echo ${days:-0}'d':${hours:-0}'h':${minutes:-0}'m':$elapsed's'
}

save_entry() {
	echo "+ $current_time" | tee -a "$log_file"
	echo -e "$@\n" | fold -s -w 30  | sed -e 's/^/\t/g' | tee -a "$log_file"
}


# CHECK ARGUMENTS
case $1 in
	a|add)
		shift
		save_entry "$@"
		;;
	t|time)
		check_file
		get_last
		get_elapsed
		get_times
		;;
	s|show)
		check_file
		less $log_file
		;;
	*)
		usage
		;;
esac
